### ISSUE TITLE
Project Collaboration - Azure Usage Billing Portal

### ISSUE THREAD

**Issue by cpumanaz** [codehollow/AzureBillingUsageSample#1]
I found your codebase and NuGet packages when trying to see if anyone has improved on the multiple rates and cost calculation for Azure.  It looks like your project could inject some life into this Usage and Billing Portal.  It's a nice to have for those of us who do not have an EA.
https://azure.microsoft.com/en-us/blog/announcing-the-release-of-the-azure-usage-and-billing-portal/

The project hasn't been updated in a while, but perhaps overhauling it with your api, and a singular web application and inexpensive Azure SQL instead of CSV you could help out many like myself who are looking to save money on Azure and be able to help others do so as well.

Cheers!  -Matt

**Comment by arminreiter** [comment]
Hey Matt,
thanks for your message and sorry for the late response. I'm currently really busy, so I'll unfortunately not find time to contribute to that project. I already thought about to join such a project or to create a simple solution that just shows the costs in a simple web application. This idea is still in my head, but as already said, I'm currently really busy, so it's on my todo list for later on.

A few weeks ago, I build an Azure Function that reads data from the billing api and sends a weekly report via mail (https://codehollow.com/2017/09/weekly-azure-billing-report-per-mail-azure-functions/). It's by sure a simple solution and the initial setup requires some steps, but maybe it helps. 

Cheers! - Armin
